# Generated by Django 3.2.9 on 2021-11-21 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Coccion', '0001_initial'),
        ('Decorador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora_inicio', models.DateTimeField()),
                ('fechahora_final', models.DateTimeField()),
                ('peso_final', models.FloatField()),
                ('fecha_entrega', models.DateField()),
                ('coccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Coccion.coccion')),
                ('decorador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Decorador.decorador')),
            ],
        ),
    ]
