# Generated by Django 3.2.9 on 2021-11-21 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleado', '0002_rename_empleados_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decorador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_pasaporte', models.CharField(blank=0, max_length=50, unique=1)),
                ('pais_origen', models.CharField(max_length=50)),
                ('experiencia', models.FloatField(default=5)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleado')),
            ],
        ),
    ]
