# Generated by Django 3.2.6 on 2021-11-23 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Decorador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decorador',
            old_name='experiencia',
            new_name='experienciaD',
        ),
        migrations.RenameField(
            model_name='decorador',
            old_name='n_pasaporte',
            new_name='n_pasaporteD',
        ),
        migrations.RenameField(
            model_name='decorador',
            old_name='pais_origen',
            new_name='pais_origenD',
        ),
    ]
