# Generated by Django 3.2.9 on 2021-11-20 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pastelero', '0002_alter_pastelero_n_pasaporte'),
        ('Solicitud', '0002_auto_20211120_1828'),
        ('Ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elaboracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientes', models.ManyToManyField(to='Ingredientes.Ingrediente')),
                ('pasteleros', models.ManyToManyField(to='Pastelero.Pastelero')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Solicitud.solicitud')),
            ],
        ),
    ]
