# Generated by Django 3.2.9 on 2021-11-20 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tipo', models.CharField(max_length=100)),
                ('peso_minimo', models.FloatField()),
                ('fecha_solicitud', models.DateField()),
                ('fecha_entrega', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleados')),
            ],
        ),
    ]
