# Generated by Django 3.2.9 on 2021-11-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_entrega',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='peso_minimo',
            field=models.CharField(max_length=50),
        ),
    ]
