# Generated by Django 3.2.6 on 2021-11-23 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingrediente',
            old_name='name',
            new_name='nameIngrediente',
        ),
    ]
