# Generated by Django 3.2.9 on 2021-11-20 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pastelero', '0002_alter_pastelero_n_pasaporte'),
        ('Solicitud', '0002_auto_20211120_1828'),
        ('Empleado', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleados',
            new_name='Empleado',
        ),
    ]
