# Generated by Django 3.2.9 on 2021-11-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pastelero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastelero',
            name='n_pasaporte',
            field=models.CharField(blank=0, max_length=50, unique=1),
        ),
    ]
