# Generated by Django 3.2.9 on 2021-11-21 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0002_rename_empleados_empleado'),
        ('Pastelero', '0002_alter_pastelero_n_pasaporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastelero',
            name='empleado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleado'),
        ),
    ]
