# Generated by Django 3.2.6 on 2021-11-23 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pastelero', '0003_alter_pastelero_empleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastelero',
            old_name='experiencia',
            new_name='experienciaP',
        ),
        migrations.RenameField(
            model_name='pastelero',
            old_name='n_pasaporte',
            new_name='n_pasaporteP',
        ),
        migrations.RenameField(
            model_name='pastelero',
            old_name='pais_origen',
            new_name='pais_origenP',
        ),
    ]
